fix error with login_credentials when config is enabled
We're invoking the credential provider chain in our production code with
no args:

```
Aws::CredentialProviderChain.new.resolve
```

This fails on 176 with a `NameError` when config is enabled:

```
NameError:
  undefined local variable or method `region' for #<Aws::CredentialProviderChain:0x00000001094dc100 @config=nil>
aws-sdk-core-3.239.1/lib/aws-sdk-core/credential_provider_chain.rb:176:in `login_credentials'
aws-sdk-core-3.239.1/lib/aws-sdk-core/credential_provider_chain.rb:13:in `block in resolve'
aws-sdk-core-3.239.1/lib/aws-sdk-core/credential_provider_chain.rb:12:in `each'
aws-sdk-core-3.239.1/lib/aws-sdk-core/credential_provider_chain.rb:12:in `resolve'
```

PR #3319[^1] inadvertently caused this error by not checking if config
was passed. Elsewhere in the file the code is guarding against that.

Write a failing test, then make it pass.

[^1]: https://github.com/aws/aws-sdk-ruby/pull/3319